// STUDIO-MAC.1 — Tauri 2 build hook.
//
// Generated by `tauri init`; left intentionally tiny. The actual
// build work (bundling, signing, notarising) is driven by the
// Tauri CLI + tauri-action in CI.

fn main() {
    tauri_build::build()
}
