-- ============================================================
-- 131: email_sequences — webhook trigger columns (FLOW2).
--
-- Adds inbound-webhook support to the sequences feature so
-- external systems (n8n, Glofox, Stripe, Zapier, anything that
-- can POST JSON) can fire any sequence the operator builds.
-- The existing trigger types (booking_created, anniversary,
-- inactivity, etc.) all fire from inside the CRM — this trigger
-- is the inverse: external system POSTs → enrol contact.
--
-- Schema additions (both nullable; only populated when the
-- sequence's trigger_type is 'webhook'):
--   webhook_token  TEXT — unique 32-char hex in the inbound URL.
--                          /api/webhooks/sequence/<token>. Auto-
--                          generated on first save of a webhook-
--                          triggered sequence (in the API route,
--                          not via DB default — operators may
--                          want to regenerate via a UI button to
--                          rotate after exposure).
--   webhook_secret TEXT — optional shared secret. When set, the
--                          receiver verifies the X-Webhook-Secret
--                          header (constant-time compare). NULL
--                          means token-in-URL is the only auth.
--
-- Why a per-sequence URL (vs a single endpoint with sequence_id
-- in the body): operator copy-pastes ONE URL into their external
-- system, no payload routing, no leaked sequence id in logs.
-- Token rotation = generate new token, give them the new URL.
--
-- The webhook STEP type (mig 087/089) is unrelated — that's an
-- OUTBOUND http call from inside a sequence step. This is the
-- INBOUND mirror.
-- ============================================================

BEGIN;

ALTER TABLE public.email_sequences
  ADD COLUMN IF NOT EXISTS webhook_token  TEXT,
  ADD COLUMN IF NOT EXISTS webhook_secret TEXT;

-- Partial unique index — only enforces uniqueness for sequences
-- that have a token set. NULL tokens (every non-webhook sequence)
-- don't need to be unique.
CREATE UNIQUE INDEX IF NOT EXISTS email_sequences_webhook_token_unique
  ON public.email_sequences(webhook_token)
  WHERE webhook_token IS NOT NULL;

COMMENT ON COLUMN public.email_sequences.webhook_token IS
  'Unique 32-char hex token in the inbound webhook URL when trigger_type=webhook. /api/webhooks/sequence/<token>. Auto-generated by the create/update API route. Mig 131.';

COMMENT ON COLUMN public.email_sequences.webhook_secret IS
  'Optional shared secret. Receiver constant-time-compares against the X-Webhook-Secret request header. NULL = token-in-URL is the only auth (still unguessable, just no second factor). Mig 131.';

COMMIT;
