-- 541 — make name_normalized the SAME ALGORITHM as normalizeName(), not a
-- list that happens to cover today's data (IG-LINK.3).
--
-- Mig 540 folded accents with a hand-curated translate() list. JS uses NFKD
-- plus combining-mark stripping. Those are not the same function, and 28 prod
-- rows already disagreed:
--   * letters missing from the list (ğ, ū, ș)
--   * names stored in NFD form — combining marks as separate codepoints,
--     visually identical to the NFC spelling, so undetectable by eye. Their
--     presence proves an import path is already delivering NFD (macOS-origin
--     CSVs and several sync sources emit it by default), so the count grows.
--   * NFKD compatibility characters — the "fancy font" display names Instagram
--     users love (𝓙, 𝕒 …), which JS folds to plain letters.
--
-- None of the 28 sat in a duplicate-name group, so they only ever failed
-- closed (no auto-link, manual path) — no wrong link happened. But the
-- ambiguity guard's soundness rests on these two normalizers agreeing, and
-- nothing enforced that; one NFD twin landing in a group reintroduces the
-- mig-540 bug in miniature. normalize() is IMMUTABLE, so the real algorithm
-- is legal in a generated column — use it and the classes above vanish.
--
-- A generated column's expression cannot be altered in place, so drop and
-- re-add. The column is derived, so there is nothing to preserve; the index
-- goes with it and is recreated below.
alter table contacts drop column if exists name_normalized;

alter table contacts
  add column name_normalized text
  generated always as (
    btrim(
      regexp_replace(
        lower(
          regexp_replace(normalize(coalesce(name, ''), NFKD), '[̀-ͯ]', '', 'g')
        ),
        '[^a-z0-9]+', ' ', 'g'
      )
    )
  ) stored;

comment on column contacts.name_normalized is
  'Accent/case/punctuation-folded contacts.name, generated by the SAME algorithm as normalizeName() in src/lib/instagram-contact-link.js (NFKD + combining-mark strip). Keeps Instagram auto-linking counting same-name duplicates over the TRUE set (IG-LINK.3, mig 541). Read-only — never write it.';

create index if not exists idx_contacts_location_name_normalized
  on contacts (location_id, name_normalized)
  where name_normalized <> '';
